Enforce uniform error reporting
UCLCSSA/API-Documentation pull request #1
Opened 2019-08-07 08:23 UTC by jieyouxu

Update docs for a uniform error reporting interface.

All 4XX 5XX error responses now has the body

```json
{
    "error": "@http-status/detailed-error-type"
}
```

With `error` being of the format `@http-status/detailed-error-type`.

This allows clients to differentiate causes of errors such as `400 Bad Request`.

2019-08-07 09:04 UTC, FYHu requested changes
Probably need to fix the table format?

2019-08-08 05:03 UTC, jieyouxu reviewed
Formatted tables.

2019-08-08 06:18 UTC, magetron approved these changes
Agreed.

2019-08-08 08:10 UTC, FYHu approved these changes

2019-08-08 08:10 UTC, merged